# Generated by Django 5.0.14 on 2026-06-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="enable_ai_personalization",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="gemini_api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
