# Generated by Django 5.0.14 on 2026-06-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_sequencestep_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignlead',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('REPLIED', 'Replied'), ('BOUNCED', 'Bounced'), ('SKIPPED', 'Skipped'), ('FINISHED', 'Finished')], default='ENROLLED', max_length=20),
        ),
    ]
