# Generated by Django 5.0.14 on 2026-06-10 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('tenants', '0002_organization_enable_ai_personalization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
            ],
            options={
                'ordering': ['domain'],
                'unique_together': {('organization', 'domain')},
            },
        ),
    ]
