# Generated by Django 5.0.14 on 2026-06-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadimportjob'),
        ('leads', '0004_tag_color'),
    ]

    operations = [
    ]
